method: system
prompt: null

per_turn_prompts:
  - name: first_turn
    condition: "current_turn == 0"
    history_mode: all
    skip_env: 0.0
    response_truncation: python_code, answer_code
    template: null
  - name: tool_response
    condition: "make_up_tool_response == True"
    history_mode: all
    skip_env: 0.0
    response_truncation: python_code, answer_code
    update_memory: false
    template: |
      Now you have received the server feedback for your last implementation. Based on that and all your previous responses, improve the implementation.

      Here is the server feedback. Please refer to this feedback to improve the implementation:
      Server feedback (status/metrics/errors):
      {feedback}

      Return an improved Triton implementation named `ModelNew` as a single ```python``` block. Let's think step by step.
